Algoritmo "VetorNome "

Var
// Seção de Declarações das variáveis
    Nomes:Vetor[1..5] de caractere
    contadorloop1:Inteiro



Inicio
      Para contadorloop1 de 1 ate 5 faca
        Escreva("Digite o nome do Estudante número" ,contadorloop1 ,"de 5:")
         leia(Nomes[contadorloop1])
      fimpara

      para contadorloop1 de 1 ate 5 faca

        Escreval("Nome do estudante ", Nomes[contadorloop1])
      
      fimpara


Fimalgoritmo